import React, { useState, useEffect } from 'react';
import { evidenceAPI } from '../services/evidenceApi';
import EvidenceGrid from '../components/evidence/EvidenceGrid';
import FilterPanel from '../components/evidence/FilterPanel';
import EvidenceDetails from '../components/evidence/EvidenceDetails';

export default function EvidenceLocker() {
  const [items, setItems] = useState([]);
  const [filtered, setFiltered] = useState([]);
  const [activeId, setActiveId] = useState(null);
  const [metadata, setMetadata] = useState(null);
  const [integrity, setIntegrity] = useState(null);
  const [search, setSearch] = useState('');
  const [filterClass, setFilterClass] = useState('All');
  const [loading, setLoading] = useState(true);

  const fetchEvidenceDetails = async (id) => {
    try {
      const [resMeta, resInteg] = await Promise.all([
        evidenceAPI.getMetadata(id),
        evidenceAPI.getIntegrity(id)
      ]);
      setMetadata(resMeta.data);
      setIntegrity(resInteg.data);
    } catch (err) {
      console.error("Failed to load evidence inspect details:", err);
    }
  };

  const fetchEvidenceList = async () => {
    try {
      const res = await evidenceAPI.getAll();
      const raw = res.data || [];
      setItems(raw);
      if (raw.length > 0) {
        const firstId = raw[0].evidence_id;
        setActiveId(firstId);
        await fetchEvidenceDetails(firstId);
      }
    } catch (err) {
      console.error("Failed to list evidence logs:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvidenceList();
  }, []);

  // Sync search and filters
  useEffect(() => {
    let result = items;
    if (search.trim()) {
      const q = search.toLowerCase();
      result = result.filter(item =>
        item.plate_number?.toLowerCase().includes(q) ||
        String(item.vehicle_id).includes(q) ||
        item.violation?.toLowerCase().includes(q)
      );
    }
    if (filterClass !== 'All') {
      result = result.filter(item =>
        item.violation?.toLowerCase() === filterClass.toLowerCase()
      );
    }
    setFiltered(result);
  }, [items, search, filterClass]);

  const handleSelect = async (id) => {
    setActiveId(id);
    await fetchEvidenceDetails(id);
  };

  const handleDelete = async (id) => {
    try {
      await evidenceAPI.deleteEvidence(id);
      const updated = items.filter(item => item.evidence_id !== id);
      setItems(updated);
      if (updated.length > 0) {
        const nextId = updated[0].evidence_id;
        setActiveId(nextId);
        await fetchEvidenceDetails(nextId);
      } else {
        setActiveId(null);
        setMetadata(null);
        setIntegrity(null);
      }
    } catch (err) {
      console.error("Failed to delete evidence log:", err);
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-slate-550 text-xs">
        <span>Loading Evidence Archive...</span>
      </div>
    );
  }

  return (
    <div className="flex-1 p-6 space-y-6 overflow-y-auto">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-slate-100 font-sans">Evidence Locker</h2>
        <p className="text-xs text-slate-500">Secure repository storing snapshots and raw recordings generated by the AI engine.</p>
      </div>

      {/* Filter panel */}
      <FilterPanel
        search={search}
        onSearchChange={setSearch}
        filterClass={filterClass}
        onFilterChange={setFilterClass}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Grid (2 cols) */}
        <div className="lg:col-span-2 space-y-6">
          <EvidenceGrid
            items={filtered}
            onSelect={handleSelect}
            onDelete={handleDelete}
          />
        </div>

        {/* Right Panel (1 col) */}
        <div className="space-y-6">
          <EvidenceDetails
            activeId={activeId}
            metadata={metadata}
            integrity={integrity}
            onDelete={handleDelete}
          />
        </div>
      </div>
    </div>
  );
}
