import React, { useState, useEffect } from 'react';
import { evidenceAPI } from '../services/evidenceApi';
import EvidenceGrid from '../components/evidence/EvidenceGrid';
import FilterPanel from '../components/evidence/FilterPanel';
import EvidenceDetails from '../components/evidence/EvidenceDetails';

export default function EvidenceLocker() {
  const [items, setItems] = useState([]);
  const [filtered, setFiltered] = useState([]);
  const [activeId, setActiveId] = useState(null);
  const [metadata, setMetadata] = useState(null);
  const [integrity, setIntegrity] = useState(null);
  const [search, setSearch] = useState('');
  const [filterClass, setFilterClass] = useState('All');
  const [loading, setLoading] = useState(true);

  const fetchEvidenceDetails = async (id) => {
    try {
      const [resDetail, resMeta, resInteg] = await Promise.all([
        evidenceAPI.getById(id),
        evidenceAPI.getMetadata(id),
        evidenceAPI.getIntegrity(id)
      ]);
      setMetadata({
        ...resDetail.data,
        ...resMeta.data
      });
      setIntegrity(resInteg.data);
    } catch (err) {
      console.error("Failed to load evidence inspect details:", err);
    }
  };

  const fetchEvidenceList = async () => {
    try {
      let res;
      if (search.trim() || filterClass !== 'All') {
        const params = {};
        if (search.trim()) {
          const q = search.trim();
          params.plate_number = q;
          params.violation_type = q;
          params.date = q;
          params.camera = q;
          if (!isNaN(q)) {
            params.evidence_id = parseInt(q);
            params.vehicle_id = parseInt(q);
          }
        }
        if (filterClass !== 'All') {
          params.violation_type = filterClass;
        }
        res = await evidenceAPI.search(params);
      } else {
        res = await evidenceAPI.getAll();
      }
      const raw = res.data || [];
      setItems(raw);
      setFiltered(raw);
      
      if (raw.length > 0) {
        const exists = raw.some(item => item.evidence_id === activeId);
        if (!exists) {
          const firstId = raw[0].evidence_id;
          setActiveId(firstId);
          await fetchEvidenceDetails(firstId);
        }
      } else {
        setActiveId(null);
        setMetadata(null);
        setIntegrity(null);
      }
    } catch (err) {
      console.error("Failed to list evidence logs:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      fetchEvidenceList();
    }, 200);

    return () => clearTimeout(delayDebounceFn);
  }, [search, filterClass]);

  const handleSelect = async (id) => {
    setActiveId(id);
    await fetchEvidenceDetails(id);
  };

  const handleDelete = async (id) => {
    try {
      await evidenceAPI.deleteEvidence(id);
      const updated = items.filter(item => item.evidence_id !== id);
      setItems(updated);
      setFiltered(updated);
      if (updated.length > 0) {
        const nextId = updated[0].evidence_id;
        setActiveId(nextId);
        await fetchEvidenceDetails(nextId);
      } else {
        setActiveId(null);
        setMetadata(null);
        setIntegrity(null);
      }
    } catch (err) {
      console.error("Failed to delete evidence log:", err);
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-slate-550 text-xs">
        <span>Loading Evidence Archive...</span>
      </div>
    );
  }

  return (
    <div className="flex-1 p-6 space-y-6 overflow-y-auto">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-slate-100 font-sans">Evidence Locker</h2>
        <p className="text-xs text-slate-500">Secure repository storing snapshots and raw recordings generated by the AI engine.</p>
      </div>

      {/* Filter panel */}
      <FilterPanel
        search={search}
        onSearchChange={setSearch}
        filterClass={filterClass}
        onFilterChange={setFilterClass}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Grid (2 cols) */}
        <div className="lg:col-span-2 space-y-6">
          <EvidenceGrid
            items={filtered}
            onSelect={handleSelect}
            onDelete={handleDelete}
          />
        </div>

        {/* Right Panel (1 col) */}
        <div className="space-y-6">
          <EvidenceDetails
            activeId={activeId}
            metadata={metadata}
            integrity={integrity}
            onDelete={handleDelete}
          />
        </div>
      </div>
    </div>
  );
}
