from fastapi import APIRouter
from app.api.v1.routes import system, camera, violation, violations, evidence, analytics, email_logs, camera_stream, detection, tracking, helmet, number_plate, ocr, seat_belt, traffic_light, driver_behavior, email, ai_command_center, upload_detection, confidence, decision_engine, replay, camera_management, statistics, reports, settings

api_router = APIRouter()

# Include system and other routers under version 1
api_router.include_router(system.router)
api_router.include_router(camera_stream.router)
api_router.include_router(camera.router)
api_router.include_router(violation.router)
api_router.include_router(violations.router)
api_router.include_router(evidence.router)
api_router.include_router(analytics.router)
api_router.include_router(email_logs.router)
api_router.include_router(email.router)
api_router.include_router(ai_command_center.router)
api_router.include_router(upload_detection.router)
api_router.include_router(confidence.router)
api_router.include_router(decision_engine.router)
api_router.include_router(replay.router)
api_router.include_router(camera_management.router)
api_router.include_router(statistics.router)
api_router.include_router(reports.router)
api_router.include_router(settings.router)
api_router.include_router(detection.router)
api_router.include_router(tracking.router)
api_router.include_router(helmet.router)
api_router.include_router(number_plate.router)
api_router.include_router(ocr.router)
api_router.include_router(seat_belt.router)
api_router.include_router(traffic_light.router)
api_router.include_router(driver_behavior.router)
